ARG BASE_TAG
FROM quay.io/rhacs-eng/apollo-ci:${BASE_TAG}

WORKDIR /home/ubuntu/test
COPY --chown=ubuntu:ubuntu test/ .
ENV CI=true
ENV CIRCLECI=false

CMD ["bats", "--print-output-on-failure", "--verbose-run", \
     "/home/ubuntu/rox-ci-image/scripts/bats/"]
