defaults: &defaults
  docker:
    - image: cimg/base:stable

version: 2.1

commands:
  build-and-push-image:
    parameters:
      tag-prefix:
        description: Prefix to be added before the tag.
        type: string
        default: ""
      dockerfile-path:
        description: Path to the Dockerfile
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            export TAG="$(git describe --tags --abbrev=10)"
            docker build images/ -f << parameters.dockerfile-path >> \
              -t "quay.io/rhacs-eng/apollo-ci:snapshot-<< parameters.tag-prefix >>$TAG" \
              -t "quay.io/rhacs-eng/apollo-ci:<< parameters.tag-prefix >>$TAG"

      - run:
          name: Push image
          command: |
            docker login -u "$QUAY_RHACS_ENG_RW_USERNAME" -p "$QUAY_RHACS_ENG_RW_PASSWORD" quay.io

            export TAG="<< parameters.tag-prefix >>$(git describe --tags --abbrev=10)"
            if [[ $CIRCLE_BRANCH = master || -n $CIRCLE_TAG ]]; then
              echo "Pushing release image"
              image_to_push="quay.io/rhacs-eng/apollo-ci:$TAG"
            else
              echo "Pushing snapshot image"
              image_to_push="quay.io/rhacs-eng/apollo-ci:snapshot-$TAG"
            fi
            docker push "${image_to_push}" | cat
            echo "${image_to_push}" > /tmp/pushed_image

      - persist_to_workspace:
          root: /tmp
          paths:
            - pushed_image


jobs:
  build-and-push-rox:
    <<: *defaults
    steps:
      - build-and-push-image:
          dockerfile-path: images/Dockerfile.rox

  unit-test-rox:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Login to quay.io
          command: |
            docker login -u "$QUAY_RHACS_ENG_RO_USERNAME" --password-stdin \<<<"$QUAY_RHACS_ENG_RO_PASSWORD" quay.io

      - run:
          name: Run unit tests for circleci-tools using the built image
          command: |
            export TAG="$(git describe --tags --abbrev=10)"
            export IMAGE="quay.io/rhacs-eng/apollo-ci:snapshot-$TAG"
            docker pull "$IMAGE"
            images/circleci-tools/test/test.bats

  create-or-update-dependent-rox-pr:
    <<: *defaults
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "c7:dd:37:f0:33:4b:a1:16:80:d6:56:48:fd:d3:6c:87"
    - attach_workspace:
        at: /tmp

    - run:
        name: Clone stackrox repo
        command: |
          git clone git@github.com:stackrox/stackrox.git /tmp/stackrox

    - run:
        name: Create commit in stackrox that updates the base image
        working_directory: /tmp/stackrox
        command: |
          pushed_image="$(cat /tmp/pushed_image)"
          [[ -n "${pushed_image}" ]]
          echo "Pushed image: ${pushed_image}"

          git config user.email "roxbot@stackrox.com"
          git config user.name "RoxBot"

          branch_name="roxbot/update-ci-image-from-${CIRCLE_PULL_REQUEST##*/}"
          git checkout "${branch_name}" || git checkout -b "${branch_name}"
          git reset --hard origin/HEAD

          sed -i 's@quay.io/rhacs-eng/apollo-ci:.*@'"${pushed_image}"' # TODO(do not merge): After upstream PR is merged, cut a tag and update this@g' .circleci/config.yml
          git commit -am "Bump base image to ${pushed_image##:}"
          git push origin "${branch_name}" --force

    - run:
        name: Create PR
        command: |
          branch_name="roxbot/update-ci-image-from-${CIRCLE_PULL_REQUEST##*/}"
          .circleci/create_update_pr_rox.sh "${branch_name}"

  check-env-for-sensitive-values:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Login to quay.io
          command: |
            docker login -u "$QUAY_RHACS_ENG_RO_USERNAME" --password-stdin \<<<"$QUAY_RHACS_ENG_RO_PASSWORD" quay.io

      - run:
          name: Use the image we have built to check our own output
          command: |
            export TAG="$(git describe --tags --abbrev=10)"
            export IMAGE="quay.io/rhacs-eng/apollo-ci:snapshot-$TAG"
            export CIRCLECI_TOKEN="$CIRCLE_TOKEN_ROXBOT"
            docker pull "$IMAGE"
            docker run --rm "$IMAGE" \
              -e CIRCLECI_TOKEN -e CIRCLE_WORKFLOW_ID \
              -e CIRCLE_PROJECT_REPONAME -e CIRCLE_BUILD_NUM \
              poll-for-workflow-completion.js 1800
            output_dir="$(mktemp -d)"
            docker run --rm "$IMAGE" \
              -e CIRCLECI_TOKEN \
              pull-workflow-output.js "$CIRCLE_WORKFLOW_ID" "$output_dir"
            env > check.env
            docker run --rm "$IMAGE" \
              check-for-sensitive-env-values.js -e check.env -b "$output_dir"
            rm check.env

  build-and-push-collector:
    <<: *defaults
    steps:
      - build-and-push-image:
          dockerfile-path: images/Dockerfile.collector
          tag-prefix: "collector-"

  build-and-push-jenkins-plugin:
    <<: *defaults
    steps:
      - build-and-push-image:
          dockerfile-path: images/Dockerfile.jenkins-plugin
          tag-prefix: "jenkins-plugin-"

workflows:
  version: 2
  build:
    jobs:
    - build-and-push-rox:
        context: quay-rhacs-eng-readwrite
        filters:
          tags:
            only: /.*/
    - unit-test-rox:
        context: quay-rhacs-eng-readonly
        requires:
        - build-and-push-rox
    - create-or-update-dependent-rox-pr:
        filters:
          branches:
            ignore: [master, gavin/RS-344-env-checks]
        requires:
        - unit-test-rox
    - check-env-for-sensitive-values:
        context: quay-rhacs-eng-readonly
        requires:
        # will change to create-or-update-dependent-rox-pr
        - unit-test-rox
    - build-and-push-collector:
        context: quay-rhacs-eng-readwrite
        filters:
          tags:
            only: /.*/
    - build-and-push-jenkins-plugin:
        context: quay-rhacs-eng-readwrite
        filters:
          tags:
            only: /.*/
