defaults: &defaults
  docker:
    - image: circleci/golang:1.10.4
  working_directory: /go/src/bitbucket.org/stack-rox/apollo-ci-image

version: 2
jobs:
  sanity:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Check environment for required secrets
        command: |
          : ${DOCKERHUB_USERNAME:?}
          : ${DOCKERHUB_PASSWORD:?}
          : ${QUAY_USERNAME:?}
          : ${QUAY_PASSWORD:?}
    - run:
        name: Check that current Git ref is describable
        command: git describe --tags

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Refresh base image
          command: docker pull circleci/golang:1.10.4 | cat

      - run:
          name: Build all
          command: |
            export TAG=$(git describe --tags --abbrev=10)
            docker build -t stackrox/apollo-ci:$TAG .

      - run:
          name: Push new Docker image
          command: |
            export TAG=$(git describe --tags --abbrev=10)

            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker push stackrox/apollo-ci:$TAG | cat

            docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io
            docker tag stackrox/apollo-ci:$TAG quay.io/stackrox/apollo-ci:$TAG | cat
            docker push quay.io/stackrox/apollo-ci:$TAG | cat

workflows:
  version: 2
  build:
    jobs:
      - sanity:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - sanity
          filters:
            tags:
              only: /.*/
