defaults: &defaults
  docker:
    - image: circleci/golang:1.11.1
  working_directory: /go/src/bitbucket.org/stack-rox/apollo-ci-image

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - setup_remote_docker

    - run:
        name: Build Docker images
        command: |
          export TAG=$(git describe --tags --abbrev=10)
          docker build \
            -t stackrox/apollo-ci:snapshot-$TAG \
            -t stackrox/apollo-ci:$TAG rox
          docker build \
            -t stackrox/apollo-ci:snapshot-$TAG-collector \
            -t stackrox/apollo-ci:$TAG-collector collector

    - run:
        name: Push Docker image
        command: |
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

          export TAG=$(git describe --tags --abbrev=10)
          if [[ $CIRCLE_BRANCH = master || -n $CIRCLE_TAG ]]; then
            echo Pushing release images
            docker push \
              stackrox/apollo-ci:$TAG \
              stackrox/apollo-ci:$TAG-collector
          else
            echo Pushing snapshot images
            docker push \
              stackrox/apollo-ci:snapshot-$TAG \
              stackrox/apollo-ci:snapshot-$TAG-collector
          fi

workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
