defaults: &defaults
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/bitbucket.org/stack-rox/apollo-ci-image

version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - setup_remote_docker

    - run:
        name: Build Docker images
        command: |
          export TAG="$(git describe --tags --abbrev=10)"
          docker build images/ -f images/Dockerfile.collector \
            -t "stackrox/apollo-ci:snapshot-collector-$TAG" \
            -t "stackrox/apollo-ci:collector-$TAG"
          docker build images/ -f images/Dockerfile.rox \
            -t "stackrox/apollo-ci:snapshot-$TAG" \
            -t "stackrox/apollo-ci:$TAG"

    - run:
        name: Push Docker image
        command: |
          docker login -u "$DOCKER_IO_PUSH_USERNAME" -p "$DOCKER_IO_PUSH_PASSWORD"

          export TAG=$(git describe --tags --abbrev=10)
          if [[ $CIRCLE_BRANCH = master || -n $CIRCLE_TAG ]]; then
            echo Pushing release images
            docker push "stackrox/apollo-ci:$TAG" | cat
            docker push "stackrox/apollo-ci:collector-$TAG" | cat
          else
            echo Pushing snapshot images
            docker push "stackrox/apollo-ci:snapshot-$TAG" | cat
            docker push "stackrox/apollo-ci:snapshot-collector-$TAG" | cat
          fi

workflows:
  version: 2
  build:
    jobs:
    - build:
        context: docker-io-push
        filters:
          tags:
            only: /.*/
