defaults: &defaults
  docker:
    - image: cimg/base:stable

version: 2.1

orbs:
  bats: circleci/bats@1.0.0

commands:
  open-test-pr:
    parameters:
      repo:
        description: Name of the repo where the PR should be opened.
        type: string
        default: ""
      image-flavor:
        description: The flavor of the apollo-ci image that the target repo uses.
        type: string
        default: ""
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c7:dd:37:f0:33:4b:a1:16:80:d6:56:48:fd:d3:6c:87"
      - run:
          name: Clone << parameters.repo >> repo
          command: |
            git clone git@github.com:stackrox/<< parameters.repo >>.git /tmp/<< parameters.repo >>
      - run:
          name: Create commit in << parameters.repo >> that updates the base image if necessary
          command: |
            if ! .circleci/changes_affect.sh << parameters.repo >>; then
              echo "No need to open/update a PR against << parameters.repo >> - current changes are not affecting this repo."
              exit 0;
            fi

            TAG="$(.circleci/get_tag.sh "<< parameters.image-flavor >>")"

            pushd "/tmp/<< parameters.repo >>"

            git config user.email "roxbot@stackrox.com"
            git config user.name "RoxBot"
            branch_name="roxbot/update-ci-image-from-${CIRCLE_PULL_REQUEST##*/}"
            if git fetch --quiet origin "${branch_name}"; then
              git checkout "${branch_name}"
              git pull --quiet --set-upstream origin "${branch_name}"
            else
              git checkout -b "${branch_name}"
              git push --set-upstream origin "${branch_name}"
            fi

            sed -i "s@\(.*\)/apollo-ci:.*@\1/apollo-ci:${TAG} # TODO(do not merge): After upstream PR is merged, cut a tag and update this@g" .circleci/config.yml

            # If the image parameter was originally quoted, we need to close the quote
            sed -i "s@\"\(.*\)/apollo-ci:${TAG} # TODO@\"\1/apollo-ci:${TAG}\" # TODO@g" .circleci/config.yml

            if git diff-index --quiet HEAD; then
              echo "There is nothing new to commit - apparently the CI job has been restarted without any new changes in the code"
            else
              git commit --allow-empty -am "Bump base image tag to ${TAG##:}"
              git push origin "${branch_name}"
            fi
            popd

            .circleci/create_update_pr.sh \
              "${branch_name}" \
              "<< parameters.repo >>" \
              "Update apollo-ci image" \
              "Bump version of apollo-ci image used in CircleCI" \
              "ci-upgrade-tests"

  build-and-push-image:
    parameters:
      image-flavor:
        description: A flavor used to tag the apollo-ci image.
        type: string
        default: ""
      dockerfile-path:
        description: Path to the Dockerfile
        type: string
      use-base:
        description: Whether to build a container image based on the base image
        type: boolean
        default: true
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build & push image
          command: |
            # Login may be required for pulling the base image for building (if used)
            docker login -u "$QUAY_RHACS_ENG_RW_USERNAME" -p "$QUAY_RHACS_ENG_RW_PASSWORD" quay.io
            BASE_TAG="$(.circleci/get_tag.sh base)"
            BUILD_ARGS=(<<# parameters.use-base >>--build-arg "BASE_TAG=$BASE_TAG"<</ parameters.use-base >>)
            TAG="$(.circleci/get_tag.sh "<< parameters.image-flavor >>")"
            docker build \
              ${BUILD_ARGS[@]} \
              -f << parameters.dockerfile-path >> \
              -t "quay.io/rhacs-eng/apollo-ci:${TAG}" \
              images/

            for i in {1..5}; do
              docker push "quay.io/rhacs-eng/apollo-ci:${TAG}" && break || sleep 15
            done

  check-image:
    parameters:
      image-flavor:
        description: The flavor of apollo-ci image to check.
        type: string
        default: ""
    steps:
      - run:
          name: Get roxctl
          command: |
            curl -k -H "Authorization: Bearer $ROX_API_TOKEN" https://$STACKROX_CENTRAL_HOST:443/api/cli/download/roxctl-linux -o roxctl
            chmod +x ./roxctl
      - run:
          name: Scan images for policy deviations and vulnerabilities
          command: |
            TAG="$(.circleci/get_tag.sh "<< parameters.image-flavor >>")"
            ./roxctl image check --endpoint "$STACKROX_CENTRAL_HOST:443" --image "quay.io/rhacs-eng/apollo-ci:${TAG}"

jobs:
  build-and-push-base:
    <<: *defaults
    steps:
      - build-and-push-image:
          dockerfile-path: images/base.Dockerfile
          image-flavor: "base"
          use-base: false

  # We separate  building of rocksdb to save CI time (~15 minutes).
  # See rocksdb.Dockerfile for more information.
  build-and-push-rocksdb:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Ensure that rocksdb container is up-to-date"
          command: |
            dockerfile_sha="($(shasum images/rocksdb.Dockerfile))"
            docker login -u "$QUAY_RHACS_ENG_RW_USERNAME" -p "$QUAY_RHACS_ENG_RW_PASSWORD" quay.io
            IMAGE="quay.io/rhacs-eng/apollo-ci:rocksdb-${dockerfile_sha}"
            if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect "$IMAGE" >/dev/null; then
              echo "Image '$IMAGE' already exists - no need to build"
            else
              echo "Image '$IMAGE' not found - building and pushing it..."
              docker build \
                -f images/rocksdb.Dockerfile \
                -t "$IMAGE" \
                images/
              docker push "$IMAGE" | cat
            fi

  build-and-push-rox:
    <<: *defaults
    steps:
      - build-and-push-image:
          dockerfile-path: images/rox.Dockerfile
          use-base: true
      - check-image

  test-cci-export:
    <<: *defaults
    resource_class: medium
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Test cci-export inside Docker
        command: |
          docker login -u "$QUAY_RHACS_ENG_RO_USERNAME" --password-stdin \<<<"$QUAY_RHACS_ENG_RO_PASSWORD" quay.io
          BASE_TAG="$(.circleci/get_tag.sh base)"

          docker build \
            --build-arg BASE_TAG="$BASE_TAG" \
            -f images/test.cci-export.Dockerfile \
            -t test.cci-export \
            images/
          docker run --rm test.cci-export

  build-and-push-env-check:
    <<: *defaults
    steps:
      - build-and-push-image:
          dockerfile-path: images/env-check.Dockerfile
          image-flavor: "env-check"
          use-base: false
      - check-image:
          image-flavor: "env-check"

  unit-test-env-check:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Login to quay.io
          command: |
            docker login -u "$QUAY_RHACS_ENG_RO_USERNAME" --password-stdin \<<<"$QUAY_RHACS_ENG_RO_PASSWORD" quay.io

      - run:
          name: Run unit tests for circleci-tools using the built image
          command: |
            TAG="$(.circleci/get_tag.sh "env-check")"
            export IMAGE="quay.io/rhacs-eng/apollo-ci:${TAG}"
            docker pull "$IMAGE"
            images/circleci-tools/test/test.bats

  check-env-for-sensitive-values:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Login to quay.io
          command: |
            docker login -u "$QUAY_RHACS_ENG_RO_USERNAME" --password-stdin \<<<"$QUAY_RHACS_ENG_RO_PASSWORD" quay.io

      - run:
          name: Check build output using the built image
          command: |
            TAG="$(.circleci/get_tag.sh "env-check")"
            export IMAGE="quay.io/rhacs-eng/apollo-ci:${TAG}"
            export CIRCLECI_TOKEN="$CIRCLE_TOKEN_ROXBOT"
            docker pull "$IMAGE"

            docker run --rm \
              -e CIRCLECI_TOKEN -e CIRCLE_WORKFLOW_ID \
              -e CIRCLE_PROJECT_REPONAME -e CIRCLE_BUILD_NUM \
              "$IMAGE" poll-for-workflow-completion.js 1800

            scratch="$(mktemp -d)"
            output_dir="$scratch/builds"
            mkdir -p "$output_dir"
            docker run -u "$(id -u):$(id -g)" --rm \
              -e CIRCLECI_TOKEN -e CIRCLE_WORKFLOW_ID \
              -e CIRCLE_PROJECT_REPONAME -e CIRCLE_BUILD_NUM \
              -v "$scratch":"$scratch":z \
              "$IMAGE" pull-workflow-output.js "$output_dir"

            env_file="$scratch/check.env"
            env > "$env_file"
            docker run -u "$(id -u):$(id -g)" --rm \
              -v "$scratch":"$scratch":z \
              "$IMAGE" check-for-sensitive-env-values.js -e "$env_file" -b "$output_dir"
            rm "$env_file"

  build-and-push-collector:
    <<: *defaults
    steps:
      - build-and-push-image:
          dockerfile-path: images/collector.Dockerfile
          image-flavor: "collector"
          use-base: false
      - check-image:
          image-flavor: "collector"

  build-and-push-jenkins-plugin:
    <<: *defaults
    steps:
      - build-and-push-image:
          dockerfile-path: images/jenkins-plugin.Dockerfile
          image-flavor: "jenkins-plugin"
          use-base: false
      - check-image:
          image-flavor: "jenkins-plugin"

  create-or-update-stackrox-repo-pr:
    <<: *defaults
    steps:
      - open-test-pr:
          repo: stackrox

  create-or-update-scanner-repo-pr:
    <<: *defaults
    steps:
      - open-test-pr:
          repo: scanner

  create-or-update-collector-repo-pr:
    <<: *defaults
    steps:
      - open-test-pr:
          repo: collector
          image-flavor: "collector"

  create-or-update-jenkins-plugin-repo-pr:
    <<: *defaults
    steps:
      - open-test-pr:
          repo: jenkins-plugin
          image-flavor: "jenkins-plugin"

workflows:
  version: 2
  build:
    jobs:
    - bats/run:
        path: ./test/bats
        filters:
          tags:
            only: /.*/
    - test-cci-export:
        context: quay-rhacs-eng-readonly
        filters:
          tags:
            only: /.*/
        requires:
        - build-and-push-base
        - bats/run
    - build-and-push-rocksdb:
        context: quay-rhacs-eng-readwrite
        filters:
          tags:
            only: /.*/
    - build-and-push-base:
        context: quay-rhacs-eng-readwrite
        filters:
          tags:
            only: /.*/
    - build-and-push-rox:
        context:
          - quay-rhacs-eng-readwrite
          - stackrox-ci-instance
        filters:
          tags:
            only: /.*/
        requires:
        - build-and-push-rocksdb
        - test-cci-export
    - build-and-push-env-check:
        context:
          - quay-rhacs-eng-readwrite
          - stackrox-ci-instance
        filters:
          tags:
            only: /.*/
        requires:
        - bats/run
    - unit-test-env-check:
        context: quay-rhacs-eng-readonly
        requires:
        - build-and-push-env-check
    - check-env-for-sensitive-values:
        context:
          - quay-rhacs-eng-readonly
          - quay-rhacs-eng-readwrite
        requires:
        - unit-test-env-check
        - build-and-push-rox
    - build-and-push-collector:
        context:
          - quay-rhacs-eng-readwrite
          - stackrox-ci-instance
        filters:
          tags:
            only: /.*/
        requires:
        - bats/run
    - build-and-push-jenkins-plugin:
        context:
          - quay-rhacs-eng-readwrite
          - stackrox-ci-instance
        filters:
          tags:
            only: /.*/
        requires:
        - bats/run
    - create-or-update-collector-repo-pr:
        filters:
          branches:
            ignore: master
        requires:
        - build-and-push-collector
    - create-or-update-stackrox-repo-pr:
        filters:
          branches:
            ignore: master
        requires:
        - build-and-push-rox
    - create-or-update-scanner-repo-pr:
        filters:
          branches:
            ignore: master
        requires:
        - build-and-push-rox
    - create-or-update-jenkins-plugin-repo-pr:
        filters:
          branches:
            ignore: master
        requires:
        - build-and-push-jenkins-plugin
