FROM circleci/golang:1.11.2-stretch

USER 0

RUN apt-get update && apt-get install -y --no-install-recommends lsb-release cmake

ENV ROX_CI_IMAGE=collector-ci-image

COPY ./static-contents/ /
RUN \
	mv /bin/bash /bin/real-bash && \
	mv /bin/bash-wrapper /bin/bash

USER circleci

# Install GCloud SDK, copied from
# https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu#before-you-begin
RUN curl https://sdk.cloud.google.com | bash

ENV PATH /home/circleci/google-cloud-sdk/bin:${PATH}
