name: Build and push image
description: Build and push image
inputs:
  image-flavor:
    description: A flavor used to tag the apollo-ci image.
    required: true
  dockerfile-path:
    description: Path to the Dockerfile
    required: true
  builds-on:
    description: The image flavor to build upon. Passed to the dockerfile as BASE_ARG.
    default: ""
runs:
  using: composite
  steps:
    - name: Build and push image
      run: |
        # Login may be required for pulling the base image for building (if used) and to omit the rate limit
        docker login -u "$QUAY_RHACS_ENG_RW_USERNAME" -p "$QUAY_RHACS_ENG_RW_PASSWORD" quay.io

        if [[ -n "${{ inputs.builds-on }}" ]]; then
          BASE_TAG="$(.circleci/get_tag.sh "${{ inputs.builds-on }}")"
          BUILD_ARGS+=(--build-arg "BASE_TAG=$BASE_TAG")
        fi

        STACKROX_CENTOS_TAG="$(cat STACKROX_CENTOS_TAG)"

        TAG="$(.circleci/get_tag.sh "${{ inputs.image-flavor }}" "${STACKROX_CENTOS_TAG}")"
        IMAGE="quay.io/rhacs-eng/apollo-ci:${TAG}"

        # The `stackrox-build` and `rocksdb` images share the centos image
        # tag through `STACKROX_CENTOS_TAG`.

        case "${{ inputs.image-flavor }}" in
            rocksdb)
                if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect "$IMAGE" >/dev/null; then
                  echo "Image '$IMAGE' already exists - no need to build it"
                  exit 0
                fi
                BUILD_ARGS+=(--build-arg "STACKROX_CENTOS_TAG=${STACKROX_CENTOS_TAG}")
                ;;
            stackrox-build)
                BUILD_ARGS+=(--build-arg "STACKROX_CENTOS_TAG=${STACKROX_CENTOS_TAG}")
                BUILD_ARGS+=(--build-arg "ROCKSDB_TAG=$(.circleci/get_tag.sh rocksdb "${STACKROX_CENTOS_TAG}")")
                ;;
        esac

        docker build \
          "${BUILD_ARGS[@]}" \
          -f ${{ inputs.dockerfile-path }} \
          -t "${IMAGE}" \
          images/

        for _ in {1..5}; do
          docker push "${IMAGE}" && break || sleep 15
        done

        for _ in {1..5}; do
          docker login -u "$QUAY_STACKROX_IO_RW_USERNAME" -p "$QUAY_STACKROX_IO_RW_PASSWORD" quay.io
          docker tag "${IMAGE}" "quay.io/stackrox-io/apollo-ci:${TAG}"
          docker push "quay.io/stackrox-io/apollo-ci:${TAG}" && break || sleep 15
        done
      shell: bash
