name: Test GitHub Actions
on:
  push:
    branches:
      - shane/rs-525-ci-migration-ERROR
    inputs:
      message:
        description: Message
        type: string
        default: hello world
        required: true
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: echo "setup"
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: |
          echo "${{ inputs.message }}"
          echo ${{ inputs.message }}
    needs: setup
  teardown:
    runs-on: ubuntu-latest
    steps:
      - name: teardown
        run: echo "teardown"
    if: "${{ always() }}"
    needs: [setup, greeting]
