name: Hello World

on:
  push:
    branches:
      - shane/rs-525-ci-migration
  pull_request:
    branches:
      - shane/rs-525-ci-migration

env:
  FOO: foo
  SSH_KEY_FINGERPRINT: "c7:dd:37:f0:33:4b:a1:16:80:d6:56:48:fd:d3:6c:87"

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      message1: ${{ steps.greeting.outputs.first }}
      message2: ${{ steps.greeting.outputs.second }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: stackrox/rox-ci-image
          path: rox-ci-image

      - name: setup
        run: mkdir -p output

      - name: greeting
        id: greeting
        env:
          MOCK_SECRET: ${{ secrets.MOCK_SECRET }}
        run: |
          # Verify capability to explicitly mask generated and mutated secrets
          MOCK_SECRET_BASE64="$(base64 <<<$MOCK_SECRET | tr -d '\r\n')"
          echo "::add-mask::$MOCK_SECRET_BASE64"
          echo "FOO                : [$FOO]"
          echo "MOCK_SECRET        : [$MOCK_SECRET]"
          echo "MOCK_SECRET_BASE64 : [$MOCK_SECRET_BASE64]"

          # Verify log capture group capability
          echo "::group::Source checkout (first 30 lines of file tree output)"
          tree -alpn . | head -n30
          echo "::endgroup::"

          # Verify secret masking in log capture group
          echo "::group::Test secret masking within a log capture group"
          echo "MOCK_SECRET_BASE64 : [$MOCK_SECRET_BASE64]"
          echo "::endgroup::"

          # Verify stand-alone script env inheritance
          ./rox-ci-image/scripts/bootstrap.sh init \
              | tee output/job-init.log

          # Verify job output mechanism
          echo "::set-output name=first::hello"
          echo "::set-output name=second::world"

          # Verify setting env var for use in subsequent steps
          echo "MY_VAR=42" >> $GITHUB_ENV

          # Demonstrate setting the step summary data
          echo "SUMMARY: [RS-525](https://issues.redhat.com/browse/RS-525)" \
              >> $GITHUB_STEP_SUMMARY

          # Demonstrate pulling event info from environment
          PULL_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PULL_NUMBER: $PULL_NUMBER"
          cp "$GITHUB_EVENT_PATH" output/event.json

      - name: test-use-step-output
        run: |
          # Verify use of step-level outputs
          echo "Step output first  : ${{ steps.greeting.outputs.first }}"
          echo "Step output second : ${{ steps.greeting.outputs.second }}"

      - name: archive build log
        uses: actions/upload-artifact@v3
        with:
          name: greeting-log
          path: |
              output/job-init.log
              output/event.json
          retention-days: 5

  build-foo:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: stackrox/rox-ci-image
          path: rox-ci-image

      - name: setup
        run: mkdir -p output

      - name: foo
        run: |
          # Verify use of job-level outputs
          echo "message1: ${{ needs.init.outputs.message1 }}"
          echo "message2: ${{ needs.init.outputs.message2 }}"
          ./rox-ci-image/scripts/bootstrap.sh foo \
              | tee output/job-foo.log

  build-bar:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: stackrox/rox-ci-image
          path: rox-ci-image

      - name: setup
        run: mkdir -p output

      - name: bar
        run: |
          # Verify use of job-level outputs
          echo "message1: ${{ needs.init.outputs.message1 }}"
          echo "message2: ${{ needs.init.outputs.message2 }}"
          ./rox-ci-image/scripts/bootstrap.sh bar \
              | tee output/job-bar.log
